name = "The Hilbert game"
version = "1.1.0"
extra_files = "extras"
intro = "src/intro.lean"

[[worlds]]
name = "Tutorial World"
id = 1
levels = [ "src/tutorial_world/level*.lean" ]

[[worlds]]
name = "Incidence World"
id = 2
parents = [1]
levels = [ "src/incidence_world/level01.lean", "src/incidence_world/level02.lean", "src/incidence_world/level03.lean", "src/incidence_world/level04.lean","src/incidence_world/level05.lean"]

